# services:
#   postgres:
#     image: postgres:17-alpine
#     environment:
#       - POSTGRES_USER=root
#       - POSTGRES_PASSWORD=secret
#       - POSTGRES_DB=simple_bank
#   api:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8080:8080"
#     depends_on:
#       - postgres
#     environment:
#       - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
#     entrypoint: [ "/app/wait-for.sh postgres:5432", "--", "/app/start.sh" ]
#     command: [ "/app/main" ]


services:
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"  # Added for debugging if needed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d simple_bank"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy  # Wait for postgres to be healthy
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable